# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{brightly}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Elliot"]
  s.date = %q{2009-11-23}
  s.default_executable = %q{brightly}
  s.description = %q{Adds syntax highlighting and some other code stuff to Markdown}
  s.email = %q{adam@warptube.com}
  s.executables = ["brightly"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/brightly",
     "brightly.gemspec",
     "config.ru",
     "lib/brightly.rb",
     "lib/brightly/provider/base.rb",
     "lib/brightly/provider/config.rb",
     "lib/brightly/provider/exec.rb",
     "lib/brightly/provider/public/stylesheets/active4d.css",
     "lib/brightly/provider/public/stylesheets/all_hallows_eve.css",
     "lib/brightly/provider/public/stylesheets/amy.css",
     "lib/brightly/provider/public/stylesheets/blackboard.css",
     "lib/brightly/provider/public/stylesheets/brilliance_black.css",
     "lib/brightly/provider/public/stylesheets/brilliance_dull.css",
     "lib/brightly/provider/public/stylesheets/cobalt.css",
     "lib/brightly/provider/public/stylesheets/dawn.css",
     "lib/brightly/provider/public/stylesheets/eiffel.css",
     "lib/brightly/provider/public/stylesheets/espresso_libre.css",
     "lib/brightly/provider/public/stylesheets/idle.css",
     "lib/brightly/provider/public/stylesheets/iplastic.css",
     "lib/brightly/provider/public/stylesheets/lazy.css",
     "lib/brightly/provider/public/stylesheets/mac_classic.css",
     "lib/brightly/provider/public/stylesheets/magicwb_amiga.css",
     "lib/brightly/provider/public/stylesheets/pastels_on_dark.css",
     "lib/brightly/provider/public/stylesheets/slush_poppies.css",
     "lib/brightly/provider/public/stylesheets/spacecadet.css",
     "lib/brightly/provider/public/stylesheets/sunburst.css",
     "lib/brightly/provider/public/stylesheets/twilight.css",
     "lib/brightly/provider/public/stylesheets/zenburnesque.css",
     "spec/brightly_spec.rb",
     "spec/data/code.html",
     "spec/data/code.markdown",
     "spec/data/double_nest.html",
     "spec/data/double_nest.markdown",
     "spec/data/javascript.html",
     "spec/data/javascript.markdown",
     "spec/data/nested.html",
     "spec/data/nested.markdown",
     "spec/data/simple.html",
     "spec/data/simple.markdown",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/adamelliot/brightly}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple standalone web app that adds syntax highlighting to Markdown}
  s.test_files = [
    "spec/brightly_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.4"])
      s.add_runtime_dependency(%q<ultraviolet>, [">= 0.10.2"])
      s.add_runtime_dependency(%q<rdiscount>, [">= 1.3.5"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5.0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0.9.4"])
      s.add_dependency(%q<ultraviolet>, [">= 0.10.2"])
      s.add_dependency(%q<rdiscount>, [">= 1.3.5"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rack-test>, [">= 0.5.0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0.9.4"])
    s.add_dependency(%q<ultraviolet>, [">= 0.10.2"])
    s.add_dependency(%q<rdiscount>, [">= 1.3.5"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rack-test>, [">= 0.5.0"])
  end
end

